### PR TITLE
search route 

### PR DESCRIPTION
**Pull request by dclermont90**
added route for search;
added controller function to call route with searchTerm parameter;
added resource to return search result

### CODE REVIEW

**Comment by vnchenko** [comment]
Route::get('/suche', 'MainPageController@search')->name('search'); 
Is this api method?

**Comment by vnchenko** [comment]
'meetings' => $this->meetings,
            'people' => $this->people,
            'organizations' => $this->organizations,
            'files' => $this->files,
            'locations' => $this->locations,
            'papers' => $this->papers,
btw, I just need themes, locations and people. Thats it.

**Comment by dclermont90** [comment]
> Route::get('/suche', 'MainPageController@search')->name('search');
> Is this api method?

This is not a api method it takes data that is stored in the database

**Comment by dclermont90** [comment]
> 'meetings' => $this->meetings,
> 'people' => $this->people,
> 'organizations' => $this->organizations,
> 'files' => $this->files,
> 'locations' => $this->locations,
> 'papers' => $this->papers,
> btw, I just need themes, locations and people. Thats it.

Ok, i basically just returned everything that was seen in the design that looks like the search.
Bildschirmfoto 2019-09-27 um 15 02 05

Since, im kinda new in this project, i don't know what decision were made and things agreed up on. Maybe @MBeckers can clarify some things here.

**Comment by MBeckers** [comment]
i think papers needs to be renamed to topics (themes).
That there is multiple data, i would let it in for know, as if the search api is responding with more then currently needed its fine.

**Comment by vnchenko** [comment]
> Ok, i basically just returned everything that was seen in the design that looks like the search.
> Bildschirmfoto 2019-09-27 um 15 02 05

Where did you get this layout? 
I have an old version?

**Comment by dclermont90** [comment]
renamed paper to topic and as discussed with @MBeckers added resource collections in search resource

**Comment by dclermont90** [comment]
> > Ok, i basically just returned everything that was seen in the design that looks like the search.
> > Bildschirmfoto 2019-09-27 um 15 02 05
> 
> Where did you get this layout?
> Do I have an old version?
> image

I got this from Marius.
@MBeckers There seems to be an issue with the design distributed, can you check that?

**Comment by MBeckers** [comment]
okay i checked, the design i send to dclermont is older then yours ivan, so last one is correct.
Sorry for the confusion.

**Pull request merged**
